name: Python application

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tkinterdnd2
        pip install ffmpeg-python
        pip install pyinstaller
      shell: pwsh

    - name: Create Executable
      run: |
        pyinstaller --noconfirm `
                --name=main `
                --console `
                --path "./main.py" `
                --add-binary "./FFMPEG/ffprobe.exe;FFMPEG/" `
                --add-binary "./FFMPEG/ffmpeg.exe;FFMPEG/" `
                --add-data "./GUI/assets;." `
                --hidden-import=PIL.Image `
                --hidden-import=PIL._tkinter_finder `
                main.py
      shell: pwsh



    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: main.exe
        path: dist/main.exe
