name: Python application

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        # ... (other pip installations)
        if (Test-Path requirements.txt) {pip install -r requirements.txt}
      shell: pwsh

    - name: Create Executable
      run: |
        pyinstaller --noconfirm \
                    --name=main \
                    --console \
                    --path "C:/Users/TedCh/OneDrive/Documents/GitHub/HAPpy/main.py" \
                    --add-binary "C:/Users/TedCh/OneDrive/Documents/GitHub/HAPpy/FFMPEG/ffprobe.exe;FFMPEG/" \
                    --add-binary "C:/Users/TedCh/OneDrive/Documents/GitHub/HAPpy/FFMPEG/ffmpeg.exe;FFMPEG/" \
                    --add-data "C:/Users/TedCh/AppData/Local/Programs/Python/Python311/Lib/site-packages/tkinterdnd2;tkinterdnd2/" \
                    --add-data "C:/Users/TedCh/OneDrive/Documents/GitHub/HAPpy/GUI/assets;GUI/assets/" \
                    --hidden-import=PIL.Image \
                    --hidden-import=PIL._tkinter_finder \
                    main.py

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: main.exe
        path: dist/main.exe
